---
version: '3'
services:
  entrolytics:
    build: ../
    #image: ghcr.io/entro314-labs/entrolytics:postgresql-latest
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgresql://entrolytics:entrolytics@db:5432/entrolytics
      DATABASE_TYPE: postgresql
      APP_SECRET: replace-me-with-a-random-string
    depends_on:
      db:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'curl http://localhost:3000/api/heartbeat']
      interval: 5s
      timeout: 5s
      retries: 5
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: entrolytics
      POSTGRES_USER: entrolytics
      POSTGRES_PASSWORD: entrolytics
    volumes:
      - entrolytics-db-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 5
  cypress:
    image: 'cypress/included:13.6.0'
    depends_on:
      - entrolytics
      - db
    environment:
      - CYPRESS_baseUrl=http://entrolytics:3000
      - CYPRESS_entrolytics_user=admin
      - CYPRESS_entrolytics_password=entrolytics
    volumes:
      - ./tsconfig.json:/tsconfig.json
      - ../cypress.config.ts:/cypress.config.ts
      - ./:/cypress
      - ../node_modules/:/node_modules
      - ../src/lib/crypto.ts:/src/lib/crypto.ts
volumes:
  entrolytics-db-data:
